<a href="https://colab.research.google.com/github/devashish10079/Data-Science/blob/main/Lec_04(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

In [2]:
import numpy as np


In [6]:
a = np.array([1,2,3,4,5,'2']) # stores only one type of data
print(a)

['1' '2' '3' '4' '5' '2']


In [8]:
np_arr = np.array([3,3,3,3.3,'hello',False])
print(bool(np_arr[-1]))

a = False
print(bool(a))

True
False


In [25]:
# np.zeros() --->>> function used to create an array filled with zeros.
a = np.zeros(3)
# print(a)

b = np.zeros((2,3),dtype = int)
# print(b)

c = np.zeros((2,3,4))
# print(c)
# print(type(a[0,0,0]))

d = np.ones((2,3,4))
# print(d)

e = np.empty(4,dtype = int) # --->>> creates a NumPy array without initializing its values.
# np.empty(shape, dtype=float)
# print(e)

f = np.full(4,5,dtype = int) # --->>> function that creates an array of a specified shape and fills every element with the same value.
# numpy.full(shape, fill_value, dtype=None)
# print(f)

g = np.arange(3,8,1,dtype = int) # --->>> function that creates an array of evenly spaced values within a given interval.
# np.arange([start], [stop],[step], dtype=None)
# print(g)

h = np.linspace(0,10,5,dtype = int,endpoint= False) # --->>> function that creates evenly spaced numbers over a specified interval.
# np.linspace(start, stop, num=50, endpoint=True)
print(h)


[0 2 4 6 8]


In [29]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a.size) # --->>>
print(a.shape) # --->>> Returns the shape (dimensions) of an array.
print(a.ndim) # --->>> Returns the number of dimensions (axes) of an array.
print(a.dtype) # --->>> Returns the data type of the elements in the array.

5
(5,)
5
(5,)


In [31]:
b = np.random.randint(1,7)
# np.random.randint(low, high=None, size=None)
print(b)

# np.random.choice() is used to randomly select element(s) from a given array or range.
# np.random.choice(a, size=None, replace=True)
c = np.random.choice(a,size = 2)
print(c)


3
[2 3]


**Broadcasting**

In [37]:
a = np.ones((5,2),dtype= int)
b = np.array([5,6,7,8,9])
c = np.ones((5,2),dtype = int)
d = np.array([1,2,3,4,])

print(c*2)
print(a+c)


# print(a*2)
# print(a+b)
# print(a-b)
# print(a/b)


[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]


In [55]:
# a = np.random.randint(2,15,6)
# a = np.array([1,2,3,4,4,5])
a = a.reshape(3,2)
# print(a)

# Reshape
b = a.reshape(3,2)
# b = np.array([1,2,3,3,4,5])
# print(b)

# Transpose
c = b.transpose()
# print(c)

# Concatenate
d = np.concatenate((a, b), axis=1)
print(d)


[[1 2 1 2]
 [3 4 3 4]
 [4 5 4 5]]


In [68]:
# Where
# np.where(condition, value_if_true, value_if_false)
# a = np.random.randint(2,15,6)
# a = np.array([1,23,25,45,423,2])
a = np.array([[1, 2],
              [3, 4]])


# b = a = np.random.randint(2,18,6)
# b = np.array([1,2,3,4,4,5])
b = np.array([[5, 6],
              [7, 8]])

c = np.where(b > 3,b,a)
# print(a)
# print(b)
# print(c)

# Sort
d = np.sort(a)
print(d)

# Sum
e = np.sum(a)
print(e)

# Max
f = np.max(a)
print(f)

# Min
g = np.min(a)
print(g)

# Unique
h = np.unique(a)
print(h)

# Matmul
g = np.matmul(a,b)
print(g)
# Mean
i = np.mean(a)
print(i)

# Median
j = np.median(a)
print(j)

# Variance
k = np.var(a)
print(k)



[[1 2]
 [3 4]]
10
4
1
[1 2 3 4]
[[19 22]
 [43 50]]
2.5
2.5
1.25
